name: Build & Test Pull Request

on: 
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.301

      - name: Restore Packages
        run: dotnet restore

      - name: Build ILVisualizer
        run: dotnet build --no-restore --configuration Release
      
      - name: Run Tests .NET 5.0
        run: dotnet test --no-build --configuration  Release